"use client";

import { useEffect, useState } from "react";
import { CornerDownRight, Trash2 } from "lucide-react";

type Redirect={id:number;source_path:string;target_path:string;status_code:number;reason?:string|null};

export default function RedirectsPage(){
 const [items,setItems]=useState<Redirect[]>([]);
 const [source,setSource]=useState(""); const [target,setTarget]=useState(""); const [reason,setReason]=useState("");
 async function load(){const r=await fetch("/api/admin/seo/redirects");const j=await r.json();setItems(j.data??[]);}
 useEffect(()=>{void load();},[]);
 async function create(e:React.FormEvent){e.preventDefault();const r=await fetch("/api/admin/seo/redirects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source_path:source.startsWith("/")?source:"/"+source,target_path:target.startsWith("/")?target:"/"+target,status_code:301,is_active:true,reason:reason||null})});if(r.ok){setSource("");setTarget("");setReason("");await load();}}
 async function remove(id:number){if(!confirm("¿Eliminar esta redirección?"))return;await fetch(`/api/admin/seo/redirects/${id}`,{method:"DELETE"});await load();}
 return <div className="w-full max-w-none space-y-6"><header><span className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--brand)]">SEO</span><h1 className="mt-2 text-3xl font-bold">Redirecciones 301</h1><p className="mt-2 text-sm text-[var(--muted)]">Toda URL histórica que cambie debe quedar registrada aquí antes de publicar la migración.</p></header><section className="space-y-6"><div className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--surface)]"><div className="divide-y divide-[var(--border)]">{items.map(item=><div key={item.id} className="grid gap-3 px-5 py-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><strong className="break-all">{item.source_path}</strong><p className="mt-1 flex items-center gap-2 break-all text-sm text-[var(--muted)]"><CornerDownRight size={15}/>{item.target_path}</p></div><button onClick={()=>remove(item.id)} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--border)] px-3 text-sm text-red-600"><Trash2 size={16}/>Eliminar</button></div>)}{!items.length&&<p className="px-5 py-10 text-center text-sm text-[var(--muted)]">Las URLs que se conservan exactamente no necesitan 301.</p>}</div></div><form onSubmit={create} className="space-y-4 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Nueva redirección</h2><input required value={source} onChange={e=>setSource(e.target.value)} placeholder="/url-antigua" className="min-h-11 w-full rounded-xl border border-[var(--border)] bg-transparent px-3"/><input required value={target} onChange={e=>setTarget(e.target.value)} placeholder="/url-nueva" className="min-h-11 w-full rounded-xl border border-[var(--border)] bg-transparent px-3"/><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Motivo" className="min-h-11 w-full rounded-xl border border-[var(--border)] bg-transparent px-3"/><button className="min-h-11 w-full rounded-xl bg-[var(--brand)] px-4 font-semibold text-white">Crear 301</button></form></section></div>;
}